package test.model;

import java.util.Date;

public class DisBrokerIncomeLog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dis_broker_income_log.id
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dis_broker_income_log.userId
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	private Long userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dis_broker_income_log.type
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dis_broker_income_log.createTime
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dis_broker_income_log.income
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	private Double income;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dis_broker_income_log.sourceUserId
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	private Long sourceuserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dis_broker_income_log.opcenterId
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	private Integer opcenterid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dis_broker_income_log.cooperatorId
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	private Integer cooperatorid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dis_broker_income_log.agentId
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	private Integer agentid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dis_broker_income_log.promoterId
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	private Integer promoterid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dis_broker_income_log.serviceRowId
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	private Long servicerowid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dis_broker_income_log.id
	 * @return  the value of dis_broker_income_log.id
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dis_broker_income_log.id
	 * @param id  the value for dis_broker_income_log.id
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dis_broker_income_log.userId
	 * @return  the value of dis_broker_income_log.userId
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public Long getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dis_broker_income_log.userId
	 * @param userid  the value for dis_broker_income_log.userId
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public void setUserid(Long userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dis_broker_income_log.type
	 * @return  the value of dis_broker_income_log.type
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dis_broker_income_log.type
	 * @param type  the value for dis_broker_income_log.type
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dis_broker_income_log.createTime
	 * @return  the value of dis_broker_income_log.createTime
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dis_broker_income_log.createTime
	 * @param createtime  the value for dis_broker_income_log.createTime
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dis_broker_income_log.income
	 * @return  the value of dis_broker_income_log.income
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public Double getIncome() {
		return income;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dis_broker_income_log.income
	 * @param income  the value for dis_broker_income_log.income
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public void setIncome(Double income) {
		this.income = income;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dis_broker_income_log.sourceUserId
	 * @return  the value of dis_broker_income_log.sourceUserId
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public Long getSourceuserid() {
		return sourceuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dis_broker_income_log.sourceUserId
	 * @param sourceuserid  the value for dis_broker_income_log.sourceUserId
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public void setSourceuserid(Long sourceuserid) {
		this.sourceuserid = sourceuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dis_broker_income_log.opcenterId
	 * @return  the value of dis_broker_income_log.opcenterId
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public Integer getOpcenterid() {
		return opcenterid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dis_broker_income_log.opcenterId
	 * @param opcenterid  the value for dis_broker_income_log.opcenterId
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public void setOpcenterid(Integer opcenterid) {
		this.opcenterid = opcenterid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dis_broker_income_log.cooperatorId
	 * @return  the value of dis_broker_income_log.cooperatorId
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public Integer getCooperatorid() {
		return cooperatorid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dis_broker_income_log.cooperatorId
	 * @param cooperatorid  the value for dis_broker_income_log.cooperatorId
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public void setCooperatorid(Integer cooperatorid) {
		this.cooperatorid = cooperatorid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dis_broker_income_log.agentId
	 * @return  the value of dis_broker_income_log.agentId
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public Integer getAgentid() {
		return agentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dis_broker_income_log.agentId
	 * @param agentid  the value for dis_broker_income_log.agentId
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public void setAgentid(Integer agentid) {
		this.agentid = agentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dis_broker_income_log.promoterId
	 * @return  the value of dis_broker_income_log.promoterId
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public Integer getPromoterid() {
		return promoterid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dis_broker_income_log.promoterId
	 * @param promoterid  the value for dis_broker_income_log.promoterId
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public void setPromoterid(Integer promoterid) {
		this.promoterid = promoterid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dis_broker_income_log.serviceRowId
	 * @return  the value of dis_broker_income_log.serviceRowId
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public Long getServicerowid() {
		return servicerowid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dis_broker_income_log.serviceRowId
	 * @param servicerowid  the value for dis_broker_income_log.serviceRowId
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public void setServicerowid(Long servicerowid) {
		this.servicerowid = servicerowid;
	}
}