package test.model;

import java.util.Date;

public class DisBrokerRelation {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dis_broker_relation.id
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dis_broker_relation.userId
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	private Long userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dis_broker_relation.directInviter
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	private Long directinviter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dis_broker_relation.indirectInviter
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	private Long indirectinviter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dis_broker_relation.createTime
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dis_broker_relation.lastModifyTime
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	private Date lastmodifytime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dis_broker_relation.level
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	private Byte level;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dis_broker_relation.inviterPath
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	private String inviterpath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dis_broker_relation.brokerType
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	private String brokertype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dis_broker_relation.typeChangeTime
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	private Date typechangetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dis_broker_relation.id
	 * @return  the value of dis_broker_relation.id
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dis_broker_relation.id
	 * @param id  the value for dis_broker_relation.id
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dis_broker_relation.userId
	 * @return  the value of dis_broker_relation.userId
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public Long getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dis_broker_relation.userId
	 * @param userid  the value for dis_broker_relation.userId
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public void setUserid(Long userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dis_broker_relation.directInviter
	 * @return  the value of dis_broker_relation.directInviter
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public Long getDirectinviter() {
		return directinviter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dis_broker_relation.directInviter
	 * @param directinviter  the value for dis_broker_relation.directInviter
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public void setDirectinviter(Long directinviter) {
		this.directinviter = directinviter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dis_broker_relation.indirectInviter
	 * @return  the value of dis_broker_relation.indirectInviter
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public Long getIndirectinviter() {
		return indirectinviter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dis_broker_relation.indirectInviter
	 * @param indirectinviter  the value for dis_broker_relation.indirectInviter
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public void setIndirectinviter(Long indirectinviter) {
		this.indirectinviter = indirectinviter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dis_broker_relation.createTime
	 * @return  the value of dis_broker_relation.createTime
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dis_broker_relation.createTime
	 * @param createtime  the value for dis_broker_relation.createTime
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dis_broker_relation.lastModifyTime
	 * @return  the value of dis_broker_relation.lastModifyTime
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public Date getLastmodifytime() {
		return lastmodifytime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dis_broker_relation.lastModifyTime
	 * @param lastmodifytime  the value for dis_broker_relation.lastModifyTime
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public void setLastmodifytime(Date lastmodifytime) {
		this.lastmodifytime = lastmodifytime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dis_broker_relation.level
	 * @return  the value of dis_broker_relation.level
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public Byte getLevel() {
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dis_broker_relation.level
	 * @param level  the value for dis_broker_relation.level
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public void setLevel(Byte level) {
		this.level = level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dis_broker_relation.inviterPath
	 * @return  the value of dis_broker_relation.inviterPath
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public String getInviterpath() {
		return inviterpath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dis_broker_relation.inviterPath
	 * @param inviterpath  the value for dis_broker_relation.inviterPath
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public void setInviterpath(String inviterpath) {
		this.inviterpath = inviterpath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dis_broker_relation.brokerType
	 * @return  the value of dis_broker_relation.brokerType
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public String getBrokertype() {
		return brokertype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dis_broker_relation.brokerType
	 * @param brokertype  the value for dis_broker_relation.brokerType
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public void setBrokertype(String brokertype) {
		this.brokertype = brokertype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dis_broker_relation.typeChangeTime
	 * @return  the value of dis_broker_relation.typeChangeTime
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public Date getTypechangetime() {
		return typechangetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dis_broker_relation.typeChangeTime
	 * @param typechangetime  the value for dis_broker_relation.typeChangeTime
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	public void setTypechangetime(Date typechangetime) {
		this.typechangetime = typechangetime;
	}
}