package test.dao;

import java.util.List;

import test.model.DisBrokerIncomeLog;

public interface DisBrokerIncomeLogMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dis_broker_income_log
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dis_broker_income_log
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	int insert(DisBrokerIncomeLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dis_broker_income_log
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	int insertSelective(DisBrokerIncomeLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dis_broker_income_log
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	DisBrokerIncomeLog selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dis_broker_income_log
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	int updateByPrimaryKeySelective(DisBrokerIncomeLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dis_broker_income_log
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	int updateByPrimaryKey(DisBrokerIncomeLog record);

	/**
     * 复杂查询
     * @return
     */
    List<Object> complexSelect();
}