package test.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.DisBrokerRelation;
import test.model.DisBrokerRelationExample;

public interface DisBrokerRelationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dis_broker_relation
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	long countByExample(DisBrokerRelationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dis_broker_relation
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	int deleteByExample(DisBrokerRelationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dis_broker_relation
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dis_broker_relation
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	int insert(DisBrokerRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dis_broker_relation
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	int insertSelective(DisBrokerRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dis_broker_relation
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	List<DisBrokerRelation> selectByExample(DisBrokerRelationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dis_broker_relation
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	DisBrokerRelation selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dis_broker_relation
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	int updateByExampleSelective(@Param("record") DisBrokerRelation record,
			@Param("example") DisBrokerRelationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dis_broker_relation
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	int updateByExample(@Param("record") DisBrokerRelation record, @Param("example") DisBrokerRelationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dis_broker_relation
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	int updateByPrimaryKeySelective(DisBrokerRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dis_broker_relation
	 * @mbg.generated  Mon Feb 05 17:10:18 CST 2018
	 */
	int updateByPrimaryKey(DisBrokerRelation record);
}